// <auto-generated />
using BlazorApp1.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp1.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420071022_AlignTableColumnNamesWithSpec")]
    partial class AlignTableColumnNamesWithSpec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Domain.Entities.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Don_Vi_Tinh_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Ten_Don_Vi_Tinh");

                    b.HasKey("Id");

                    b.HasIndex("TenDonViTinh")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Don_Vi_Tinh_Ten_Don_Vi_Tinh");

                    b.ToTable("tbl_DM_Don_Vi_Tinh", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Loai_San_Pham_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<string>("MaLsp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Ma_LSP");

                    b.Property<string>("TenLsp")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Ten_LSP");

                    b.HasKey("Id");

                    b.HasIndex("MaLsp")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Loai_San_Pham_Ma_LSP");

                    b.HasIndex("TenLsp")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Loai_San_Pham_Ten_LSP");

                    b.ToTable("tbl_DM_Loai_San_Pham", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
