using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BlazorApp1.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AlignSchemaForBai2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'tbl_dm_don_vi_tinh'
                    ) AND EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'tbl_DM_Don_Vi_Tinh'
                    ) THEN
                        INSERT INTO tbl_dm_don_vi_tinh (ten_don_vi_tinh, ghi_chu)
                        SELECT TRIM(src."Ten_Don_Vi_Tinh"), LEFT(src."Ghi_Chu", 255)
                        FROM "tbl_DM_Don_Vi_Tinh" src
                        WHERE src."Ten_Don_Vi_Tinh" IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1
                              FROM tbl_dm_don_vi_tinh d
                              WHERE UPPER(d.ten_don_vi_tinh) = UPPER(TRIM(src."Ten_Don_Vi_Tinh"))
                          );

                        DROP TABLE "tbl_DM_Don_Vi_Tinh";
                    ELSIF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'tbl_DM_Don_Vi_Tinh'
                    ) THEN
                        ALTER TABLE "tbl_DM_Don_Vi_Tinh" RENAME TO tbl_dm_don_vi_tinh;
                        ALTER TABLE tbl_dm_don_vi_tinh RENAME COLUMN "ID" TO don_vi_tinh_id;
                        ALTER TABLE tbl_dm_don_vi_tinh RENAME COLUMN "Ten_Don_Vi_Tinh" TO ten_don_vi_tinh;
                        ALTER TABLE tbl_dm_don_vi_tinh RENAME COLUMN "Ghi_Chu" TO ghi_chu;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE IF EXISTS tbl_dm_don_vi_tinh
                ALTER COLUMN ghi_chu TYPE varchar(255);

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_tbl_dm_don_vi_tinh_ten_don_vi_tinh"
                    ON tbl_dm_don_vi_tinh (ten_don_vi_tinh);
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS tbl_dm_loai_san_pham (
                    loai_san_pham_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ma_lsp varchar(50) NOT NULL,
                    ten_lsp varchar(120) NOT NULL,
                    ghi_chu varchar(255) NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_tbl_dm_loai_san_pham_ma_lsp"
                    ON tbl_dm_loai_san_pham (ma_lsp);

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_tbl_dm_loai_san_pham_ten_lsp"
                    ON tbl_dm_loai_san_pham (ten_lsp);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS tbl_dm_loai_san_pham;
                """);
        }
    }
}
