// <auto-generated />
using System;
using BlazorApp1.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp1.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Domain.Entities.DonViTinh", b =>
                {
                    b.Property<int>("Don_Vi_Tinh_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Don_Vi_Tinh_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Don_Vi_Tinh_ID"));

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Ten_Don_Vi_Tinh");

                    b.HasKey("Don_Vi_Tinh_ID");

                    b.HasIndex("Ten_Don_Vi_Tinh")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Don_Vi_Tinh_Ten_Don_Vi_Tinh");

                    b.ToTable("tbl_DM_Don_Vi_Tinh", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.Kho", b =>
                {
                    b.Property<int>("Kho_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Kho_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Kho_ID"));

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<string>("Ten_Kho")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Ten_Kho");

                    b.HasKey("Kho_ID");

                    b.HasIndex("Ten_Kho")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Kho_Ten_Kho");

                    b.ToTable("tbl_DM_Kho", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.KhoUser", b =>
                {
                    b.Property<int>("Kho_User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Kho_User_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Kho_User_ID"));

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Kho_ID");

                    b.Property<string>("Ma_Dang_Nhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Ma_Dang_Nhap");

                    b.HasKey("Kho_User_ID");

                    b.HasIndex("Kho_ID")
                        .HasDatabaseName("IX_tbl_DM_Kho_User_Kho_ID");

                    b.HasIndex("Ma_Dang_Nhap", "Kho_ID")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Kho_User_Ma_Dang_Nhap_Kho_ID");

                    b.ToTable("tbl_DM_Kho_User", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.LoaiSanPham", b =>
                {
                    b.Property<int>("Loai_San_Pham_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Loai_San_Pham_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Loai_San_Pham_ID"));

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<string>("Ma_LSP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Ma_LSP");

                    b.Property<string>("Ten_LSP")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Ten_LSP");

                    b.HasKey("Loai_San_Pham_ID");

                    b.HasIndex("Ma_LSP")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Loai_San_Pham_Ma_LSP");

                    b.HasIndex("Ten_LSP")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Loai_San_Pham_Ten_LSP");

                    b.ToTable("tbl_DM_Loai_San_Pham", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("NCC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NCC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NCC_ID"));

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<string>("Ma_NCC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Ma_NCC");

                    b.Property<string>("Ten_NCC")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Ten_NCC");

                    b.HasKey("NCC_ID");

                    b.HasIndex("Ma_NCC")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_NCC_Ma_NCC");

                    b.HasIndex("Ten_NCC")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_NCC_Ten_NCC");

                    b.ToTable("tbl_DM_NCC", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.NhapKho", b =>
                {
                    b.Property<int>("Nhap_Kho_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Nhap_Kho_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Nhap_Kho_ID"));

                    b.Property<string>("Don_Vi_Tien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("Don_Vi_Tien");

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Kho_ID");

                    b.Property<int>("NCC_ID")
                        .HasColumnType("integer")
                        .HasColumnName("NCC_ID");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Nhap_Kho");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("So_Phieu_Nhap_Kho");

                    b.HasKey("Nhap_Kho_ID");

                    b.HasIndex("Kho_ID")
                        .HasDatabaseName("IX_tbl_XNK_Nhap_Kho_Kho_ID");

                    b.HasIndex("NCC_ID")
                        .HasDatabaseName("IX_tbl_XNK_Nhap_Kho_NCC_ID");

                    b.HasIndex("Ngay_Nhap_Kho")
                        .HasDatabaseName("IX_tbl_XNK_Nhap_Kho_Ngay_Nhap_Kho");

                    b.HasIndex("So_Phieu_Nhap_Kho")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_XNK_Nhap_Kho_So_Phieu_Nhap_Kho");

                    b.ToTable("tbl_XNK_Nhap_Kho", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_XNK_Nhap_Kho_Don_Vi_Tien_Valid", "\"Don_Vi_Tien\" IN ('VND','USD')");

                            t.HasCheckConstraint("CK_tbl_XNK_Nhap_Kho_Ngay_Nhap_Kho_MinDate", "\"Ngay_Nhap_Kho\" >= DATE '2000-01-01'");
                        });
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.NhapKhoRawData", b =>
                {
                    b.Property<int>("Nhap_Kho_Raw_Data_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Nhap_Kho_Raw_Data_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Nhap_Kho_Raw_Data_ID"));

                    b.Property<decimal>("Don_Gia_Nhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Don_Gia_Nhap");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<int>("Nhap_Kho_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Nhap_Kho_ID");

                    b.Property<decimal>("SL_Nhap")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("SL_Nhap");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("integer")
                        .HasColumnName("San_Pham_ID");

                    b.HasKey("Nhap_Kho_Raw_Data_ID");

                    b.HasIndex("Nhap_Kho_ID")
                        .HasDatabaseName("IX_tbl_DM_Nhap_Kho_Raw_Data_Nhap_Kho_ID");

                    b.HasIndex("San_Pham_ID")
                        .HasDatabaseName("IX_tbl_DM_Nhap_Kho_Raw_Data_San_Pham_ID");

                    b.HasIndex("Nhap_Kho_ID", "San_Pham_ID", "Is_Active")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Nhap_Kho_Raw_Data_Nhap_Kho_ID_San_Pham_ID_Active")
                        .HasFilter("\"Is_Active\" = TRUE");

                    b.ToTable("tbl_DM_Nhap_Kho_Raw_Data", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_DM_Nhap_Kho_Raw_Data_Don_Gia_Nhap_Positive", "\"Don_Gia_Nhap\" > 0");

                            t.HasCheckConstraint("CK_tbl_DM_Nhap_Kho_Raw_Data_SL_Nhap_Positive", "\"SL_Nhap\" > 0");
                        });
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.SanPham", b =>
                {
                    b.Property<int>("San_Pham_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("San_Pham_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("San_Pham_ID"));

                    b.Property<int>("Don_Vi_Tinh_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Don_Vi_Tinh_ID");

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<int>("Loai_San_Pham_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Loai_San_Pham_ID");

                    b.Property<string>("Ma_San_Pham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Ma_San_Pham");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Ten_San_Pham");

                    b.HasKey("San_Pham_ID");

                    b.HasIndex("Don_Vi_Tinh_ID")
                        .HasDatabaseName("IX_tbl_DM_San_Pham_Don_Vi_Tinh_ID");

                    b.HasIndex("Loai_San_Pham_ID")
                        .HasDatabaseName("IX_tbl_DM_San_Pham_Loai_San_Pham_ID");

                    b.HasIndex("Ma_San_Pham")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_San_Pham_Ma_San_Pham");

                    b.ToTable("tbl_DM_San_Pham", (string)null);
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.XuatKho", b =>
                {
                    b.Property<int>("Xuat_Kho_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Xuat_Kho_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Xuat_Kho_ID"));

                    b.Property<string>("Don_Vi_Tien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("Don_Vi_Tien");

                    b.Property<string>("Ghi_Chu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("Ngay_Xuat_Kho")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Xuat_Kho");

                    b.Property<string>("So_Phieu_Xuat_Kho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("So_Phieu_Xuat_Kho");

                    b.HasKey("Xuat_Kho_ID");

                    b.HasIndex("Kho_ID")
                        .HasDatabaseName("IX_tbl_XNK_Xuat_Kho_Kho_ID");

                    b.HasIndex("Ngay_Xuat_Kho")
                        .HasDatabaseName("IX_tbl_XNK_Xuat_Kho_Ngay_Xuat_Kho");

                    b.HasIndex("So_Phieu_Xuat_Kho")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_XNK_Xuat_Kho_So_Phieu_Xuat_Kho");

                    b.ToTable("tbl_XNK_Xuat_Kho", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_XNK_Xuat_Kho_Don_Vi_Tien_Valid", "\"Don_Vi_Tien\" IN ('VND','USD')");

                            t.HasCheckConstraint("CK_tbl_XNK_Xuat_Kho_Ngay_Xuat_Kho_MinDate", "\"Ngay_Xuat_Kho\" >= DATE '2000-01-01'");
                        });
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.XuatKhoRawData", b =>
                {
                    b.Property<int>("Xuat_Kho_Raw_Data_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Xuat_Kho_Raw_Data_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Xuat_Kho_Raw_Data_ID"));

                    b.Property<decimal>("Don_Gia_Xuat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Don_Gia_Xuat");

                    b.Property<bool>("Is_Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<decimal>("SL_Xuat")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("SL_Xuat");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("integer")
                        .HasColumnName("San_Pham_ID");

                    b.Property<int>("Xuat_Kho_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Xuat_Kho_ID");

                    b.HasKey("Xuat_Kho_Raw_Data_ID");

                    b.HasIndex("San_Pham_ID")
                        .HasDatabaseName("IX_tbl_DM_Xuat_Kho_Raw_Data_San_Pham_ID");

                    b.HasIndex("Xuat_Kho_ID")
                        .HasDatabaseName("IX_tbl_DM_Xuat_Kho_Raw_Data_Xuat_Kho_ID");

                    b.HasIndex("Xuat_Kho_ID", "San_Pham_ID", "Is_Active")
                        .IsUnique()
                        .HasDatabaseName("UQ_tbl_DM_Xuat_Kho_Raw_Data_Xuat_Kho_ID_San_Pham_ID_Active")
                        .HasFilter("\"Is_Active\" = TRUE");

                    b.ToTable("tbl_DM_Xuat_Kho_Raw_Data", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_DM_Xuat_Kho_Raw_Data_Don_Gia_Xuat_Positive", "\"Don_Gia_Xuat\" > 0");

                            t.HasCheckConstraint("CK_tbl_DM_Xuat_Kho_Raw_Data_SL_Xuat_Positive", "\"SL_Xuat\" > 0");
                        });
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.KhoUser", b =>
                {
                    b.HasOne("BlazorApp1.Domain.Entities.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_Kho_User_tbl_DM_Kho_Kho_ID");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.NhapKho", b =>
                {
                    b.HasOne("BlazorApp1.Domain.Entities.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_XNK_Nhap_Kho_tbl_DM_Kho_Kho_ID");

                    b.HasOne("BlazorApp1.Domain.Entities.NhaCungCap", "NCC")
                        .WithMany()
                        .HasForeignKey("NCC_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_XNK_Nhap_Kho_tbl_DM_NCC_NCC_ID");

                    b.Navigation("Kho");

                    b.Navigation("NCC");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.NhapKhoRawData", b =>
                {
                    b.HasOne("BlazorApp1.Domain.Entities.NhapKho", "Nhap_Kho")
                        .WithMany("Nhap_Kho_Raw_Datas")
                        .HasForeignKey("Nhap_Kho_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_XNK_Nhap_Kho_Nhap_Kho_ID");

                    b.HasOne("BlazorApp1.Domain.Entities.SanPham", "San_Pham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_DM_San_Pham_San_Pham_ID");

                    b.Navigation("Nhap_Kho");

                    b.Navigation("San_Pham");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("BlazorApp1.Domain.Entities.DonViTinh", "Don_Vi_Tinh")
                        .WithMany()
                        .HasForeignKey("Don_Vi_Tinh_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_San_Pham_tbl_DM_Don_Vi_Tinh_Don_Vi_Tinh_ID");

                    b.HasOne("BlazorApp1.Domain.Entities.LoaiSanPham", "Loai_San_Pham")
                        .WithMany()
                        .HasForeignKey("Loai_San_Pham_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_San_Pham_tbl_DM_Loai_San_Pham_Loai_San_Pham_ID");

                    b.Navigation("Don_Vi_Tinh");

                    b.Navigation("Loai_San_Pham");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.XuatKho", b =>
                {
                    b.HasOne("BlazorApp1.Domain.Entities.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_XNK_Xuat_Kho_tbl_DM_Kho_Kho_ID");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.XuatKhoRawData", b =>
                {
                    b.HasOne("BlazorApp1.Domain.Entities.SanPham", "San_Pham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_Xuat_Kho_Raw_Data_tbl_DM_San_Pham_San_Pham_ID");

                    b.HasOne("BlazorApp1.Domain.Entities.XuatKho", "Xuat_Kho")
                        .WithMany("Xuat_Kho_Raw_Datas")
                        .HasForeignKey("Xuat_Kho_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbl_DM_Xuat_Kho_Raw_Data_tbl_XNK_Xuat_Kho_Xuat_Kho_ID");

                    b.Navigation("San_Pham");

                    b.Navigation("Xuat_Kho");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.NhapKho", b =>
                {
                    b.Navigation("Nhap_Kho_Raw_Datas");
                });

            modelBuilder.Entity("BlazorApp1.Domain.Entities.XuatKho", b =>
                {
                    b.Navigation("Xuat_Kho_Raw_Datas");
                });
#pragma warning restore 612, 618
        }
    }
}
