using BlazorApp1.Components;
using BlazorApp1.Infrastructure.Data;
using BlazorApp1.Services;
using BlazorApp1.Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace BlazorApp1;

/// <summary>
/// Diem vao khoi dong ung dung Blazor Server va khoi tao ha tang du lieu.
/// </summary>
public sealed class Program
{
    /// <summary>
    /// Cau hinh DI, pipeline va chay web host.
    /// </summary>
    public static async Task Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services
            .AddRazorComponents()
            .AddInteractiveServerComponents();

        var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            throw new InvalidOperationException("Missing connection string 'DefaultConnection'.");
        }

        // Cau hinh PostgreSQL cho ung dung Blazor + EF Core.
        builder.Services.AddDbContextFactory<AppDbContext>(options =>
            options.UseNpgsql(connectionString));

        builder.Services.AddScoped<IDonViTinhService, DonViTinhService>();
        builder.Services.AddScoped<ILoaiSanPhamService, LoaiSanPhamService>();

        var app = builder.Build();

        if (!app.Environment.IsDevelopment())
        {
            app.UseExceptionHandler("/Error", createScopeForErrors: true);
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseAntiforgery();

        app.MapRazorComponents<App>()
            .AddInteractiveServerRenderMode();

        var autoMigrate = builder.Configuration.GetValue<bool>("Database:AutoMigrateOnStartup");
        await InitializeDatabaseAsync(app, autoMigrate);

        await app.RunAsync();
    }

    /// <summary>
    /// Ap migration de tao/cap nhat schema khi khoi dong.
    /// </summary>
    private static async Task InitializeDatabaseAsync(WebApplication app, bool autoMigrate)
    {
        await using var scope = app.Services.CreateAsyncScope();
        var logger = scope.ServiceProvider
            .GetRequiredService<ILoggerFactory>()
            .CreateLogger<Program>();
        var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
        await using var dbContext = await dbFactory.CreateDbContextAsync();

        try
        {
            if (autoMigrate)
            {
                await dbContext.Database.MigrateAsync();
            }

            await EnsureAssignmentTablesAsync(dbContext);
        }
        catch (PostgresException ex) when (ex.SqlState == "28P01")
        {
            logger.LogError(ex, "Sai thong tin dang nhap PostgreSQL (username/password).");
            throw new InvalidOperationException(
                "PostgreSQL authentication failed for 'ConnectionStrings:DefaultConnection'. " +
                "Vui long kiem tra Username/Password trong appsettings hoac User Secrets.",
                ex);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Khong the khoi tao co so du lieu cho bai 1 va bai 2.");
            throw;
        }
    }

    private static async Task EnsureAssignmentTablesAsync(AppDbContext dbContext)
    {
        // Dung CREATE IF NOT EXISTS de startup an toan khi migration va script assignment cung ton tai.
        var sql = """
                  CREATE TABLE IF NOT EXISTS "tbl_DM_Don_Vi_Tinh" (
                      "Don_Vi_Tinh_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ten_Don_Vi_Tinh" varchar(100) NOT NULL,
                      "Ghi_Chu" varchar(255) NULL
                  );

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Don_Vi_Tinh_Ten_Don_Vi_Tinh"
                      ON "tbl_DM_Don_Vi_Tinh" ("Ten_Don_Vi_Tinh");

                  CREATE TABLE IF NOT EXISTS "tbl_DM_Loai_San_Pham" (
                      "Loai_San_Pham_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ma_LSP" varchar(50) NOT NULL,
                      "Ten_LSP" varchar(120) NOT NULL,
                      "Ghi_Chu" varchar(255) NULL
                  );

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Loai_San_Pham_Ma_LSP"
                      ON "tbl_DM_Loai_San_Pham" ("Ma_LSP");

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Loai_San_Pham_Ten_LSP"
                      ON "tbl_DM_Loai_San_Pham" ("Ten_LSP");
                  """;

        await dbContext.Database.ExecuteSqlRawAsync(sql);
    }
}
