using BlazorApp1.Components;
using BlazorApp1.Infrastructure.Data;
using BlazorApp1.Services;
using BlazorApp1.Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace BlazorApp1;

/// <summary>
/// Diem vao khoi dong ung dung Blazor Server va khoi tao ha tang du lieu.
/// </summary>
public sealed class Program
{
    /// <summary>
    /// Cau hinh DI, pipeline va chay web host.
    /// </summary>
    public static async Task Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services
            .AddRazorComponents()
            .AddInteractiveServerComponents();

        var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            throw new InvalidOperationException("Missing connection string 'DefaultConnection'.");
        }

        // Cau hinh PostgreSQL cho ung dung Blazor + EF Core.
        builder.Services.AddDbContextFactory<AppDbContext>(options =>
            options.UseNpgsql(connectionString));

        builder.Services.AddScoped<IDonViTinhService, DonViTinhService>();
        builder.Services.AddScoped<ILoaiSanPhamService, LoaiSanPhamService>();
        builder.Services.AddScoped<ISanPhamService, SanPhamService>();
        builder.Services.AddScoped<INhaCungCapService, NhaCungCapService>();
        builder.Services.AddScoped<IKhoService, KhoService>();
        builder.Services.AddScoped<IKhoUserService, KhoUserService>();
        builder.Services.AddScoped<INhapKhoService, NhapKhoService>();
        builder.Services.AddScoped<IXuatKhoService, XuatKhoService>();

        var app = builder.Build();

        if (!app.Environment.IsDevelopment())
        {
            app.UseExceptionHandler("/Error", createScopeForErrors: true);
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseAntiforgery();

        app.MapRazorComponents<App>()
            .AddInteractiveServerRenderMode();

        var autoMigrate = builder.Configuration.GetValue<bool>("Database:AutoMigrateOnStartup");
        await InitializeDatabaseAsync(app, autoMigrate);
        await app.RunAsync();
    }

    /// <summary>
    /// Ap migration de tao/cap nhat schema khi khoi dong.
    /// </summary>
    private static async Task InitializeDatabaseAsync(WebApplication app, bool autoMigrate)
    {
        await using var scope = app.Services.CreateAsyncScope();
        var logger = scope.ServiceProvider
            .GetRequiredService<ILoggerFactory>()
            .CreateLogger<Program>();
        var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
        await using var dbContext = await dbFactory.CreateDbContextAsync();

        try
        {
            if (autoMigrate)
            {
                await dbContext.Database.MigrateAsync();
            }

            await EnsureAssignmentTablesAsync(dbContext);
        }
        catch (PostgresException ex) when (ex.SqlState == "28P01")
        {
            logger.LogError(ex, "Sai thong tin dang nhap PostgreSQL (username/password).");
            throw new InvalidOperationException(
                "PostgreSQL authentication failed for 'ConnectionStrings:DefaultConnection'. " +
                "Vui long kiem tra Username/Password trong appsettings hoac User Secrets.",
                ex);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Khong the khoi tao co so du lieu cho bai 1 den bai 13.");
            throw;
        }
    }

    private static async Task EnsureAssignmentTablesAsync(AppDbContext dbContext)
    {
        // Dung CREATE IF NOT EXISTS de startup an toan khi migration va script assignment cung ton tai.
        var sql = """
                  CREATE TABLE IF NOT EXISTS "tbl_DM_Don_Vi_Tinh" (
                      "Don_Vi_Tinh_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ten_Don_Vi_Tinh" varchar(100) NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_Don_Vi_Tinh"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Don_Vi_Tinh_Ten_Don_Vi_Tinh"
                      ON "tbl_DM_Don_Vi_Tinh" ("Ten_Don_Vi_Tinh");

                  CREATE TABLE IF NOT EXISTS "tbl_DM_Loai_San_Pham" (
                      "Loai_San_Pham_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ma_LSP" varchar(50) NOT NULL,
                      "Ten_LSP" varchar(120) NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_Loai_San_Pham"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Loai_San_Pham_Ma_LSP"
                      ON "tbl_DM_Loai_San_Pham" ("Ma_LSP");

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Loai_San_Pham_Ten_LSP"
                      ON "tbl_DM_Loai_San_Pham" ("Ten_LSP");

                  CREATE TABLE IF NOT EXISTS "tbl_DM_San_Pham" (
                      "San_Pham_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ma_San_Pham" varchar(50) NOT NULL,
                      "Ten_San_Pham" varchar(200) NOT NULL,
                      "Loai_San_Pham_ID" integer NOT NULL,
                      "Don_Vi_Tinh_ID" integer NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_San_Pham"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_San_Pham_Ma_San_Pham"
                      ON "tbl_DM_San_Pham" ("Ma_San_Pham");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_San_Pham_Loai_San_Pham_ID"
                      ON "tbl_DM_San_Pham" ("Loai_San_Pham_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_San_Pham_Don_Vi_Tinh_ID"
                      ON "tbl_DM_San_Pham" ("Don_Vi_Tinh_ID");

                  DO $$
                  BEGIN
                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_San_Pham_tbl_DM_Loai_San_Pham_Loai_San_Pham_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_San_Pham"
                              ADD CONSTRAINT "FK_tbl_DM_San_Pham_tbl_DM_Loai_San_Pham_Loai_San_Pham_ID"
                              FOREIGN KEY ("Loai_San_Pham_ID")
                              REFERENCES "tbl_DM_Loai_San_Pham" ("Loai_San_Pham_ID")
                              ON DELETE RESTRICT;
                      END IF;

                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_San_Pham_tbl_DM_Don_Vi_Tinh_Don_Vi_Tinh_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_San_Pham"
                              ADD CONSTRAINT "FK_tbl_DM_San_Pham_tbl_DM_Don_Vi_Tinh_Don_Vi_Tinh_ID"
                              FOREIGN KEY ("Don_Vi_Tinh_ID")
                              REFERENCES "tbl_DM_Don_Vi_Tinh" ("Don_Vi_Tinh_ID")
                              ON DELETE RESTRICT;
                      END IF;
                  END $$;

                  CREATE TABLE IF NOT EXISTS "tbl_DM_NCC" (
                      "NCC_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ma_NCC" varchar(50) NOT NULL,
                      "Ten_NCC" varchar(150) NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_NCC"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_NCC_Ma_NCC"
                      ON "tbl_DM_NCC" ("Ma_NCC");

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_NCC_Ten_NCC"
                      ON "tbl_DM_NCC" ("Ten_NCC");

                  CREATE TABLE IF NOT EXISTS "tbl_DM_Kho" (
                      "Kho_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ten_Kho" varchar(150) NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_Kho"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Kho_Ten_Kho"
                      ON "tbl_DM_Kho" ("Ten_Kho");

                  CREATE TABLE IF NOT EXISTS "tbl_DM_Kho_User" (
                      "Kho_User_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Ma_Dang_Nhap" varchar(100) NOT NULL,
                      "Kho_ID" integer NOT NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_Kho_User"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_DM_Kho_User_Ma_Dang_Nhap_Kho_ID"
                      ON "tbl_DM_Kho_User" ("Ma_Dang_Nhap", "Kho_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_Kho_User_Kho_ID"
                      ON "tbl_DM_Kho_User" ("Kho_ID");

                  DO $$
                  BEGIN
                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Kho_User_tbl_DM_Kho_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_Kho_User"
                              ADD CONSTRAINT "FK_tbl_DM_Kho_User_tbl_DM_Kho_Kho_ID"
                              FOREIGN KEY ("Kho_ID")
                              REFERENCES "tbl_DM_Kho" ("Kho_ID")
                              ON DELETE RESTRICT;
                      END IF;
                  END $$;

                  DO $$
                  BEGIN
                      IF EXISTS (
                          SELECT 1
                          FROM information_schema.tables
                          WHERE table_schema = 'public'
                            AND table_name = 'tbl_DM_Nhap_Kho'
                      )
                      AND NOT EXISTS (
                          SELECT 1
                          FROM information_schema.tables
                          WHERE table_schema = 'public'
                            AND table_name = 'tbl_XNK_Nhap_Kho'
                      ) THEN
                          ALTER TABLE "tbl_DM_Nhap_Kho" RENAME TO "tbl_XNK_Nhap_Kho";
                      END IF;
                  END $$;

                  CREATE TABLE IF NOT EXISTS "tbl_XNK_Nhap_Kho" (
                      "Nhap_Kho_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "So_Phieu_Nhap_Kho" varchar(50) NOT NULL,
                      "Kho_ID" integer NOT NULL,
                      "NCC_ID" integer NOT NULL,
                      "Ngay_Nhap_Kho" date NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_XNK_Nhap_Kho"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  DO $$
                  BEGIN
                      IF EXISTS (
                          SELECT 1
                          FROM information_schema.tables
                          WHERE table_schema = 'public'
                            AND table_name = 'tbl_DM_Nhap_Kho'
                      ) THEN
                          INSERT INTO "tbl_XNK_Nhap_Kho" (
                              "Nhap_Kho_ID",
                              "So_Phieu_Nhap_Kho",
                              "Kho_ID",
                              "NCC_ID",
                              "Ngay_Nhap_Kho",
                              "Ghi_Chu",
                              "Is_Active")
                          SELECT
                              dm."Nhap_Kho_ID",
                              dm."So_Phieu_Nhap_Kho",
                              dm."Kho_ID",
                              dm."NCC_ID",
                              dm."Ngay_Nhap_Kho",
                              dm."Ghi_Chu",
                              COALESCE(dm."Is_Active", TRUE)
                          FROM "tbl_DM_Nhap_Kho" dm
                          WHERE NOT EXISTS (
                              SELECT 1
                              FROM "tbl_XNK_Nhap_Kho" x
                              WHERE x."Nhap_Kho_ID" = dm."Nhap_Kho_ID"
                          )
                          AND NOT EXISTS (
                              SELECT 1
                              FROM "tbl_XNK_Nhap_Kho" x
                              WHERE UPPER(x."So_Phieu_Nhap_Kho") = UPPER(dm."So_Phieu_Nhap_Kho")
                          );
                      END IF;
                  END $$;

                  DO $$
                  BEGIN
                      IF EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'UQ_tbl_DM_Nhap_Kho_So_Phieu_Nhap_Kho'
                      ) AND NOT EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'UQ_tbl_XNK_Nhap_Kho_So_Phieu_Nhap_Kho'
                      ) THEN
                          ALTER INDEX "UQ_tbl_DM_Nhap_Kho_So_Phieu_Nhap_Kho" RENAME TO "UQ_tbl_XNK_Nhap_Kho_So_Phieu_Nhap_Kho";
                      END IF;

                      IF EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'IX_tbl_DM_Nhap_Kho_Kho_ID'
                      ) AND NOT EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'IX_tbl_XNK_Nhap_Kho_Kho_ID'
                      ) THEN
                          ALTER INDEX "IX_tbl_DM_Nhap_Kho_Kho_ID" RENAME TO "IX_tbl_XNK_Nhap_Kho_Kho_ID";
                      END IF;

                      IF EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'IX_tbl_DM_Nhap_Kho_NCC_ID'
                      ) AND NOT EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'IX_tbl_XNK_Nhap_Kho_NCC_ID'
                      ) THEN
                          ALTER INDEX "IX_tbl_DM_Nhap_Kho_NCC_ID" RENAME TO "IX_tbl_XNK_Nhap_Kho_NCC_ID";
                      END IF;

                      IF EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'IX_tbl_DM_Nhap_Kho_Ngay_Nhap_Kho'
                      ) AND NOT EXISTS (
                          SELECT 1 FROM pg_indexes
                          WHERE schemaname = 'public'
                            AND indexname = 'IX_tbl_XNK_Nhap_Kho_Ngay_Nhap_Kho'
                      ) THEN
                          ALTER INDEX "IX_tbl_DM_Nhap_Kho_Ngay_Nhap_Kho" RENAME TO "IX_tbl_XNK_Nhap_Kho_Ngay_Nhap_Kho";
                      END IF;
                  END $$;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_XNK_Nhap_Kho_So_Phieu_Nhap_Kho"
                      ON "tbl_XNK_Nhap_Kho" ("So_Phieu_Nhap_Kho");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_XNK_Nhap_Kho_Kho_ID"
                      ON "tbl_XNK_Nhap_Kho" ("Kho_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_XNK_Nhap_Kho_NCC_ID"
                      ON "tbl_XNK_Nhap_Kho" ("NCC_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_XNK_Nhap_Kho_Ngay_Nhap_Kho"
                      ON "tbl_XNK_Nhap_Kho" ("Ngay_Nhap_Kho");

                  DO $$
                  BEGIN
                      IF EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Nhap_Kho_tbl_DM_Kho_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_XNK_Nhap_Kho"
                              DROP CONSTRAINT "FK_tbl_DM_Nhap_Kho_tbl_DM_Kho_Kho_ID";
                      END IF;

                      IF EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Nhap_Kho_tbl_DM_NCC_NCC_ID'
                      ) THEN
                          ALTER TABLE "tbl_XNK_Nhap_Kho"
                              DROP CONSTRAINT "FK_tbl_DM_Nhap_Kho_tbl_DM_NCC_NCC_ID";
                      END IF;

                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_XNK_Nhap_Kho_tbl_DM_Kho_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_XNK_Nhap_Kho"
                              ADD CONSTRAINT "FK_tbl_XNK_Nhap_Kho_tbl_DM_Kho_Kho_ID"
                              FOREIGN KEY ("Kho_ID")
                              REFERENCES "tbl_DM_Kho" ("Kho_ID")
                              ON DELETE RESTRICT;
                      END IF;

                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_XNK_Nhap_Kho_tbl_DM_NCC_NCC_ID'
                      ) THEN
                          ALTER TABLE "tbl_XNK_Nhap_Kho"
                              ADD CONSTRAINT "FK_tbl_XNK_Nhap_Kho_tbl_DM_NCC_NCC_ID"
                              FOREIGN KEY ("NCC_ID")
                              REFERENCES "tbl_DM_NCC" ("NCC_ID")
                              ON DELETE RESTRICT;
                      END IF;
                  END $$;

                  CREATE TABLE IF NOT EXISTS "tbl_DM_Nhap_Kho_Raw_Data" (
                      "Nhap_Kho_Raw_Data_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Nhap_Kho_ID" integer NOT NULL,
                      "San_Pham_ID" integer NOT NULL,
                      "SL_Nhap" numeric(18,2) NOT NULL,
                      "Don_Gia_Nhap" numeric(18,2) NOT NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_Nhap_Kho_Raw_Data"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_Nhap_Kho_Raw_Data_Nhap_Kho_ID"
                      ON "tbl_DM_Nhap_Kho_Raw_Data" ("Nhap_Kho_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_Nhap_Kho_Raw_Data_San_Pham_ID"
                      ON "tbl_DM_Nhap_Kho_Raw_Data" ("San_Pham_ID");

                  DO $$
                  BEGIN
                      IF EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_DM_Nhap_Kho_Nhap_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_Nhap_Kho_Raw_Data"
                              DROP CONSTRAINT "FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_DM_Nhap_Kho_Nhap_Kho_ID";
                      END IF;

                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_XNK_Nhap_Kho_Nhap_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_Nhap_Kho_Raw_Data"
                              ADD CONSTRAINT "FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_XNK_Nhap_Kho_Nhap_Kho_ID"
                              FOREIGN KEY ("Nhap_Kho_ID")
                              REFERENCES "tbl_XNK_Nhap_Kho" ("Nhap_Kho_ID")
                              ON DELETE RESTRICT;
                      END IF;

                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_DM_San_Pham_San_Pham_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_Nhap_Kho_Raw_Data"
                              ADD CONSTRAINT "FK_tbl_DM_Nhap_Kho_Raw_Data_tbl_DM_San_Pham_San_Pham_ID"
                              FOREIGN KEY ("San_Pham_ID")
                              REFERENCES "tbl_DM_San_Pham" ("San_Pham_ID")
                              ON DELETE RESTRICT;
                      END IF;
                  END $$;

                  CREATE TABLE IF NOT EXISTS "tbl_XNK_Xuat_Kho" (
                      "Xuat_Kho_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "So_Phieu_Xuat_Kho" varchar(50) NOT NULL,
                      "Kho_ID" integer NOT NULL,
                      "Ngay_Xuat_Kho" date NOT NULL,
                      "Ghi_Chu" varchar(255) NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_XNK_Xuat_Kho"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE UNIQUE INDEX IF NOT EXISTS "UQ_tbl_XNK_Xuat_Kho_So_Phieu_Xuat_Kho"
                      ON "tbl_XNK_Xuat_Kho" ("So_Phieu_Xuat_Kho");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_XNK_Xuat_Kho_Kho_ID"
                      ON "tbl_XNK_Xuat_Kho" ("Kho_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_XNK_Xuat_Kho_Ngay_Xuat_Kho"
                      ON "tbl_XNK_Xuat_Kho" ("Ngay_Xuat_Kho");

                  DO $$
                  BEGIN
                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_XNK_Xuat_Kho_tbl_DM_Kho_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_XNK_Xuat_Kho"
                              ADD CONSTRAINT "FK_tbl_XNK_Xuat_Kho_tbl_DM_Kho_Kho_ID"
                              FOREIGN KEY ("Kho_ID")
                              REFERENCES "tbl_DM_Kho" ("Kho_ID")
                              ON DELETE RESTRICT;
                      END IF;
                  END $$;

                  CREATE TABLE IF NOT EXISTS "tbl_DM_Xuat_Kho_Raw_Data" (
                      "Xuat_Kho_Raw_Data_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Xuat_Kho_ID" integer NOT NULL,
                      "San_Pham_ID" integer NOT NULL,
                      "SL_Xuat" numeric(18,2) NOT NULL,
                      "Don_Gia_Xuat" numeric(18,2) NOT NULL,
                      "Is_Active" boolean NOT NULL DEFAULT TRUE
                  );

                  ALTER TABLE "tbl_DM_Xuat_Kho_Raw_Data"
                      ADD COLUMN IF NOT EXISTS "Is_Active" boolean NOT NULL DEFAULT TRUE;

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_Xuat_Kho_Raw_Data_Xuat_Kho_ID"
                      ON "tbl_DM_Xuat_Kho_Raw_Data" ("Xuat_Kho_ID");

                  CREATE INDEX IF NOT EXISTS "IX_tbl_DM_Xuat_Kho_Raw_Data_San_Pham_ID"
                      ON "tbl_DM_Xuat_Kho_Raw_Data" ("San_Pham_ID");

                  DO $$
                  BEGIN
                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Xuat_Kho_Raw_Data_tbl_XNK_Xuat_Kho_Xuat_Kho_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_Xuat_Kho_Raw_Data"
                              ADD CONSTRAINT "FK_tbl_DM_Xuat_Kho_Raw_Data_tbl_XNK_Xuat_Kho_Xuat_Kho_ID"
                              FOREIGN KEY ("Xuat_Kho_ID")
                              REFERENCES "tbl_XNK_Xuat_Kho" ("Xuat_Kho_ID")
                              ON DELETE RESTRICT;
                      END IF;

                      IF NOT EXISTS (
                          SELECT 1
                          FROM pg_constraint
                          WHERE conname = 'FK_tbl_DM_Xuat_Kho_Raw_Data_tbl_DM_San_Pham_San_Pham_ID'
                      ) THEN
                          ALTER TABLE "tbl_DM_Xuat_Kho_Raw_Data"
                              ADD CONSTRAINT "FK_tbl_DM_Xuat_Kho_Raw_Data_tbl_DM_San_Pham_San_Pham_ID"
                              FOREIGN KEY ("San_Pham_ID")
                              REFERENCES "tbl_DM_San_Pham" ("San_Pham_ID")
                              ON DELETE RESTRICT;
                      END IF;
                  END $$;
                  """;

        await dbContext.Database.ExecuteSqlRawAsync(sql);
    }
}
